argparse_cfg:
  gpus:
    bind_to: processor_cfg.gpus
    help: number of gpus
  batch_size:
    bind_to: processor_cfg.batch_size
  checkpoint:
    bind_to: processor_cfg.checkpoint
    help: the checkpoint file to load from
    default: mmskeleton://st_gcn/ntu-xsub

processor_cfg:
  name: ".processor.recognition.test"
  checkpoint:

  # model setting
  model_cfg:
    name: ".models.backbones.ST_GCN"
    in_channels: 6
    ##num_class: 60
    num_class: 60
    dropout: 0.5
    edge_importance_weighting: True
    graph_cfg:
      layout: "ntu-rgb+d"
      strategy: "spatial"

  # dataset setting
  dataset_cfg:
    name: ".datasets.SkeletonFeeder"
    data_path: ./data/NTU-RGB-D/xsub/val_data.npy
    label_path: ./data/NTU-RGB-D/xsub/val_label.pkl
    # debug: true

  # dataloader setting
  #batch_size: 256
  #gpus: 4

  batch_size: 256
  gpus: 2
